name: Build PowerShell Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: 'Repo'

      - name: Create PowerShell Manifest
        uses: mod-posh/CreatePowerShellManifest@main  # Replace with your repository details for the createpowershellmanifest action
        with:
          ModuleName: 'SpnLibrary'
          Source: 'Repo'  # Use the custom path here
          Imports: 'public'
          Debug: 'true'

      - name: Create PowerShell Module
        uses: mod-posh/CreatePowerShellModule@main  # Replace with your repository details for the createpowershellmodule action
        with:
          ModuleName: 'SpnLibrary'
          Source: 'Repo'  # Use the custom path here
          Imports: 'public'
          Debug: 'true'

      - name: Upload PowerShell Module
        uses: actions/upload-artifact@v4
        with:
          name: your-module-output
          path: ${{ github.workspace }}/output