name: Build PowerShell Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: MySuperModule  # Custom path for the checkout

      - name: Create PowerShell Manifest
        uses: your-username/your-repo@v1  # Replace with your repository details for the createpowershellmanifest action
        with:
          ModuleName: 'your-module'
          Source: 'MySuperModule'  # Use the custom path here
          Debug: 'true'

      - name: Create PowerShell Module
        uses: your-username/your-repo@v1  # Replace with your repository details for the createpowershellmodule action
        with:
          ModuleName: 'your-module'
          Source: 'MySuperModule'  # Use the custom path here
          Imports: 'folder1,folder2'
          Debug: 'true'

      - name: Upload PowerShell Module
        uses: actions/upload-artifact@v2
        with:
          name: your-module-output
          path: ${{ github.workspace }}/output